name: app_farma_scan_v2
description: Aplicación para digitalizar documentos empresariales de manera rápida y sencilla.


publish_to: 'none' 


version: 2.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  dropdown_button2: 2.0.0
  easy_debounce: 2.0.1
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 4.0.3
  intl: 0.18.1
  json_path: 0.4.1
  page_transition: 2.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  provider: 6.0.4
  shared_preferences: 2.0.15
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  sqflite: 2.2.6
  timeago: 3.2.2
  url_launcher: ^6.1.14
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  cupertino_icons: ^1.0.0
  quickalert: ^1.0.1
  loading_animation_widget: ^1.2.0+4
  image_picker: ^1.0.7
  flutter_barcode_scanner: ^2.0.0
  image: ^4.1.3
  flutter_image_compress: ^2.1.0
  mask_text_input_formatter: ^2.8.0
  scanbot_sdk: ^4.2.0
  image_cropper: ^4.0.1
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/favicon.png"
  adaptative_icon_background: "ffffff"
  adaptative_icon_foreground: "assets/images/adaptative.png"

flutter_native_splash:
  color: "ffffff"
  image: "assets/images/favicon.jpg"


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
